name: node_js CI

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [18, 20]
    continue-on-error: ${{ matrix.node == 20 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nodejs Env
        run: echo "NODE_VER=`cat .nvmrc`" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Run Coverage
        uses: codecov/codecov-action@v3
